### ISSUE TITLE
我想请教一下，关于client_id问题

### ISSUE THREAD

**Issue by haitanghuadeng** [AndrewCarterUK/mqtt-cli-subscriber#1]
作为客户端，我想获取在获取发布某主题的client_id信息。因为在做物联网传输时，总是碰到主题发布问题。多个传感器发布相同主题，但是他们的id是不同的。所以，想请教一下。

**Comment by AndrewCarterUK** [comment]
你好，

不幸的是，这是不可能的。这是MQTT协议中的限制，并且发布者客户端ID不可供消费者/订户使用。

您可能必须在消息的有效负载中添加一些引用。

--------------------------

Hello,

Unfortunately it is not possible to do this. This is a restriction in the MQTT protocol, and the publisher client id is not available to a consumer/subscriber.

You may have to put some reference in the payload of the message.
